//! Build-time steps that shape `csp.exe`.
//!
//! 1. Stamps the Windows app icon onto the binary (Explorer, taskbar and console read it straight
//!    from the exe). `Pepperoni.ico` is committed at the repo root: unlike the model and the
//!    runtime it is small, so it lives in the repo rather than being a build-time prerequisite.
//! 2. Encrypts the embedded BiRefNet model. The plaintext named by [`MODEL_FILE`] at the repo
//!    root (gitignored) is read here, encrypted under a key generated fresh for this build, and
//!    written to `$OUT_DIR/model.onnx.enc`; the key+nonce go to `$OUT_DIR/model_key.rs`. The
//!    encrypted name is fixed so swapping which model ships is one edit here, not two.
//!    So the plaintext model is never `include_bytes!`'d into the image and never lands in git — see
//!    `core::shot_classifier::birefnet`, which decrypts it in memory at load. This is obfuscation,
//!    not secrecy: the key ships in the binary. `src/core/shot_classifier/cipher.rs` is the shared
//!    XOR-symmetric ChaCha20 keystream, pulled in here by path so encrypt and decrypt agree.

#[allow(dead_code)]
#[path = "src/core/shot_classifier/cipher.rs"]
mod cipher;

use std::path::Path;

/// Which model gets baked into this build. The repo root holds more than one
/// export (the 512 fp32 original, the 384 int8 quantization); this constant is
/// the only thing that decides which one ships.
const MODEL_FILE: &str = "birefnet_lite_384_int8.onnx";

fn main() {
    #[cfg(windows)]
    {
        println!("cargo:rerun-if-changed=Pepperoni.ico");
        winresource::WindowsResource::new()
            .set_icon("Pepperoni.ico")
            .compile()
            .expect("embedding Pepperoni.ico failed");
    }

    encrypt_model();
}

/// Read the plaintext model, encrypt it under a fresh key, and emit the encrypted blob plus a
/// generated key module into `OUT_DIR`.
fn encrypt_model() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");

    let model = Path::new(&manifest).join(MODEL_FILE);
    println!("cargo:rerun-if-changed={MODEL_FILE}");
    println!("cargo:rerun-if-changed=src/core/shot_classifier/cipher.rs");

    let mut bytes = std::fs::read(&model)
        .unwrap_or_else(|e| panic!("read {}: {e}", model.display()));

    let (key, nonce) = fresh_key_nonce();
    cipher::xor_keystream(&mut bytes, &key, &nonce);

    std::fs::write(Path::new(&out_dir).join("model.onnx.enc"), &bytes)
        .expect("write encrypted model");

    let key_rs = format!(
        "// Generated by build.rs — fresh per build, never committed.\n\
         pub const MODEL_KEY: [u8; 32] = {key:?};\n\
         pub const MODEL_NONCE: [u8; 12] = {nonce:?};\n",
    );
    std::fs::write(Path::new(&out_dir).join("model_key.rs"), key_rs).expect("write key module");
}

/// A key and nonce unique to this build. Obfuscation-grade entropy: a splitmix64 stream seeded from
/// the wall clock and pid. It only has to differ from build to build and stay out of source — the
/// ceiling on this whole scheme is that the key ends up in the binary regardless.
fn fresh_key_nonce() -> ([u8; 32], [u8; 12]) {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0);
    let mut s = nanos ^ ((std::process::id() as u64) << 32);

    let mut next = || {
        s = s.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = s;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    };

    let mut key = [0u8; 32];
    for c in key.chunks_mut(8) {
        c.copy_from_slice(&next().to_le_bytes());
    }
    let mut nonce = [0u8; 12];
    for c in nonce.chunks_mut(8) {
        let n = c.len();
        c.copy_from_slice(&next().to_le_bytes()[..n]);
    }
    (key, nonce)
}
